version: "3"

services:
    app:
        container_name: wearperformance
        restart: always
        image: 127.0.0.1:5000/wearperformance
        build: .
        environment: 
            - "PORT=${PORT}"
        ports: 
            - "${PORT}:${PORT}"